### ISSUE TITLE
MIT license contradicted by README

### ISSUE THREAD

**Issue by antoine-sachet** [StevenLShafer/stanpumpR#22]
The package is under MIT license, which explicitly allows commercial use.

Yet the following excerpt from the README attempts to restrict commercial use and even states "all rights reserved".

```
Companies seeking to develop such systems should contact Dr. Shafer to request written permission to incorporate stanpumpR into their products. 
Without written permission, stanpumpR must not be incorporated into commercially available systems.
```

It is inconsistent and, although I am not a lawyer, I would imagine the MIT license superseeds your note anyway.

**Comment by StevenLShafer** [comment]
Thank you! Your point is well taken. 

I'll probably need to speak with a lawyer about how to resolve this. I want the code to be freely available, based on the MIT license. However, I am anxious about companies taking the code, building it into drug delivery systems, and hurting patients because they don't know what they are doing. 

As you point it, it looks like I'm trying to have it both ways, and that is inconsistent.  Thank you for this.
